---
title: "report"
author: "ZJH"
date: "2022/5/13"
output:
  word_document: default
  html_document: 
    df_print: paged
---

# library import 
```{R,include = FALSE}

library(caret)  
library(car)
library(glmnet)  
library(GGally)
library(h2o)          # an extremely fast java-based platform
library(lmtest)
library(magrittr)
library(nnet)
library(rsample)      # data splitting 
library(randomForest) # basic implementation
library(ranger)       # a faster implementation of randomForest       # an aggregator package for performing many machine learning models
library(pheatmap)
library(tidyverse)
library(forecast)
```

# data import
```{R,include = FALSE}
set.seed(100)
tea <- readRDS('nonglin_tea.RDS')
analyze_data <- readRDS('analyze.RDS')
weather <-  analyze_data %>% select(.,c(caffeine ,acu_mean_temp:Solar_rad_MJM2))

# png('var_scatter_hist_weather_chem.png',width = 3400,height=3400)
# scatter_hist_plot(weather_chem)
# dev.off()
```
#data cleaning
```{r}
numeric_dat <- analyze_data %>% select(.,-c(key,level,observe_ys,observe_date:sample_label,FAA:total_catechins,G1L:O9L,cutting_height,tea_buds_cm,year,season,temp_differ))
numeric_dat <- analyze_data %>% select(.,-c(key,observe_ys,cultivar,observe_date:sample_label,G1L:O9L,year,temp_differ))
chem <- analyze_data %>% select(,c(polyphenol:ECG,level))
table(chem$level)
chem$level <- factor(chem$level) %>% as.numeric()
chem$level <- ifelse(chem$level>1,1,0)
test_idx <- sample(1:138,size = 30)
train_idx <- not(1:138 %in% test_idx)
chem_test <- chem[test_idx,]
chem_train <- chem[train_idx,]
chem_test_y <- chem_test$level
```

# functions include
```{r}
simple_roc <- function(labels, scores){
  labels <- labels[order(scores, decreasing=TRUE)]
  data.frame(TPR=cumsum(labels)/sum(labels), FPR=cumsum(!labels)/sum(!labels), labels)
}
```
```{r}
  importanceplot <- function(pp=and_rf) {
    i_scores <- varImp(pp, conditional=TRUE)
  #Gathering rownames in 'var'  and converting it to the factor
  #to provide 'fill' parameter for the bar chart.
  i_scores <- i_scores %>% tibble::rownames_to_column("var")
  i_scores$var<- i_scores$var %>% as.factor()

  #Plotting the bar and polar charts for comparing variables
  i_bar <- ggplot(data = i_scores) +
    geom_bar(
      stat = "identity",#it leaves the data without count and bin
      mapping = aes(x = var, y=Overall, fill = var),
      show.legend = FALSE,
      width = 1
    ) +
    labs(x = NULL, y = NULL)
  i_bar + coord_flip() + theme_minimal()
  }

```
```{r,include = FALSE}
cross_validation <- function(y_pred,ytest){
  y_pred <- ifelse(y_pred<=0.75,'B','C')
  ytest <- chem_test$level
  print(table(y_pred,ytest))
}
```
# data explore
```{R}
ggplot(data=tea,aes(observe_ys,tea_kind,color=cultivar))+
  geom_point()+
  facet_wrap(~cultivar)
```

```{R}
ggplot(data=tea,aes(observe_ys,cutting_height,color=cultivar))+
  geom_point()+
  facet_wrap(~cultivar)
```


```{R}
ggplot(data=tea,aes(observe_ys,cutting_height,color=cultivar))+
  geom_point()+
  facet_wrap(~cultivar)
```

```{R}
ggplot(data=tea,aes(duration_oc,cutting_height,color=cultivar))+
  geom_point()+
  facet_wrap(~cultivar)
```


```{r}
train_idx <- sample(1:138,108)
test_idx <- !(1:138 %in%train_idx)
train <- numeric_dat[train_idx,]
test <- numeric_dat[test_idx,]
xtrain <- model.matrix(polyphenol~., train)[,-1]
ytrain <- train$polyphenol

ytest <- test$polyphenol
xtest <- model.matrix(polyphenol~., test)[,-1]
season7th <- 0
xtest <- cbind(xtest,season7th)
lambdas_to_try <- 10^seq(-3, 7, length.out = 100)
lasso_cv <- cv.glmnet(xtrain, ytrain, alpha = 1, lambda = lambdas_to_try)
plot(lasso_cv)
best_lambda_lasso <- lasso_cv$lambda.min
lasso_mod <- glmnet(xtrain, ytrain, alpha = 1, lambda = best_lambda_lasso)
predict.glmnet(lasso_mod, type = 'coefficients')
fit <- lm(polyphenol~leaf_number+duration_oc+Total_leaf+acu_mean_temp,data = test)
lasso_pred <- predict(lasso_mod,  newx = xtest)
lm_pred <- predict(fit)

```


```{r}
mean((lasso_pred-ytest)^2)
mean((lm_pred-ytest)^2)
```

```{r}
train_idx <- sample(1:138,108)
test_idx <- !(1:138 %in%train_idx)
train <- numeric_dat[train_idx,]
test <- numeric_dat[test_idx,]

xtrain <- model.matrix(polyphenol~.+acu_mean_temp*RH*Solar_rad_H*Solar_rad_MJM2, train)[,-1]
ytrain <- train$polyphenol
ytest <- test$polyphenol
xtest <- model.matrix(polyphenol~.+acu_mean_temp*RH*Solar_rad_H*Solar_rad_MJM2, test)[,-1] %>%  as_tibble()%>% as.matrix()
data_polyphenol <- analyze_data %>% select(., c(cultivar,rain,polyphenol,acu_mean_temp,RH,Solar_rad_H,Solar_rad_MJM2))
and_rf <- randomForest(polyphenol~.+acu_mean_temp*RH*Solar_rad_H*Solar_rad_MJM2, data = data_polyphenol[train_idx,])
and_pred <- predict(and_rf,data_polyphenol[test_idx,])
(mean((and_pred-ytest)^2)/var(ytest))^0.5
accuracy(and_pred,ytest)
importanceplot()
```
```{r}
xtrain <- model.matrix(FAA~., train)[,-1]
ytrain <- train$FAA
ytest <- test$FAA
xtest <- model.matrix(FAA~., test)[,-1] %>%  as_tibble()  %>% as.matrix()
data_FAA <- analyze_data %>% select(., c(cultivar,FAA,rain,acu_mean_temp,RH,Solar_rad_H,Solar_rad_MJM2))
and_rf <- randomForest(FAA~., data = data_FAA[train_idx,])
and_pred <- predict(and_rf,data_FAA[test_idx,])
(mean((and_pred-ytest)^2)/var(ytest))^0.5
importanceplot()
```

```{r}
xtrain <- model.matrix(Gallic_Acid~., train)[,-1]
ytrain <- train$Gallic_Acid
ytest <- test$Gallic_Acid
xtest <- model.matrix(Gallic_Acid~., test)[,-1] %>%  as_tibble()  %>% as.matrix()
data_Gallic_Acid <- analyze_data %>%  select(., c(cultivar,rain,Gallic_Acid,acu_mean_temp,RH,Solar_rad_H,Solar_rad_MJM2))
and_rf <- randomForest(Gallic_Acid~., data = data_Gallic_Acid[train_idx,])
and_pred <- predict(and_rf,data_Gallic_Acid[test_idx,])
(mean((and_pred-ytest)^2)/var(ytest))^0.5
importanceplot()
```
```{r}
xtrain <- model.matrix(GC~., train)[,-1]
ytrain <- train$GC
ytest <- test$GC
xtest <- model.matrix(GC~., test)[,-1] %>%  as_tibble() %>% as.matrix()
data_GC <- analyze_data %>%  select(., c(cultivar,rain,GC,acu_mean_temp,RH,Solar_rad_H,Solar_rad_MJM2))
and_rf <- randomForest(GC~., data = data_GC[train_idx,])
and_pred <- predict(and_rf,data_GC[test_idx,])
(mean((and_pred-ytest)^2)/var(ytest))^0.5
importanceplot()
```
```{r}
xtrain <- model.matrix(GCG~., train)[,-1]
ytrain <- train$GCG
ytest <- test$GCG
xtest <- model.matrix(GCG~., test)[,-1] %>%  as_tibble() %>% as.matrix()
data_GCG <- analyze_data %>% select(., c(cultivar,GCG,rain,acu_mean_temp,RH,Solar_rad_H,Solar_rad_MJM2))
and_rf <- randomForest(GCG~., data = data_GCG[train_idx,])
and_pred <- predict(and_rf,data_GCG[test_idx,])
(mean((and_pred-ytest)^2)/var(ytest))^0.5
importanceplot()
```

```{r}
xtrain <- model.matrix(Catechin~., train)[,-1]
ytrain <- train$Catechin
ytest <- test$Catechin
xtest <- model.matrix(Catechin~., test)[,-1] %>%  as_tibble() %>% as.matrix()
data_caffeine <- analyze_data %>% select(., c(cultivar,Catechin,rain,acu_mean_temp,RH,Solar_rad_H,Solar_rad_MJM2))
and_rf <- randomForest(Catechin~., data = data_caffeine[train_idx,])
and_pred <- predict(and_rf,data_caffeine[test_idx,])
(mean((and_pred-ytest)^2)/var(ytest))^0.5
importanceplot()
```
# level~chem
```{r}
pr_chem <- prcomp(scale(chem) )
biplot(pr_chem)
importanceplot()
```

```{r}
xtrain <- model.matrix(level~., train)[,-1]
ytrain <- train$level
ytest <- test$level
xtest <- model.matrix(level~., test)[,-1] %>%  as_tibble() %>% as.matrix()
data_level <- analyze_data %>% select(., c(polyphenol:total_catechins,level))
data_level$level <- factor(data_level$level)
and_rf <- randomForest(level~., data = data_level[train_idx,])
and_pred <- predict(and_rf,data_level[test_idx,])
table(data_level[test_idx,]$level,and_pred)
importanceplot()


logit_level <- glm(level~caffeine+GCG ,data=chem_train,family=binomial())
summary(logit_level)
predicted_level <- predict(logit_level,chem_test)
predicted_level <- ifelse(predicted_level<=0.7,'B','C')
table(chem_test$level ,predicted_level)

```




```{r}
# 1.建立空的線性迴歸(只有截距項)
null <- glm(level~1 ,data=chem_train,family=binomial())
full <- glm(level~. ,data=chem_train,family=binomial())

# 2.使用step()，一個一個把變數丟進去
forward.lm = step(null, 
                  # 從空模型開始，一個一個丟變數，
                  # 最大不會超過完整的線性迴歸
                  # (一定要加上界 upper=full，不可以不加) 
                  scope=list(lower=null, upper=full), 
                  direction="forward")
y_pred_forward <- predict(forward.lm,chem_test)
cross_validation(y_pred_forward,chem_test_y)

backward.lm = step(full, 
                  # 這裡可以加下界(lower=null)，也可以不加
                  scope = list(upper=full), 
                  direction="backward")  
y_pred_backward <- predict(backward.lm,chem_test)
cross_validation(y_pred_backward,chem_test_y)
```

```{R}
# lasso & ridge for chem ----
ridge = glmnet(x = as.matrix(chem[, -13]), 
               y = chem[, 13], 
               alpha = 0,
               family = "binomial")

lasso = glmnet(x = as.matrix(chem[, -13]), 
               y = chem[, 13], 
               alpha = 1,
               family = "binomial")

par(mfcol = c(1, 2)) # cool!!
plot(lasso, xvar='lambda', main="Lasso")
plot(ridge, xvar='lambda', main="Ridge")
```
```{R}
# 經由 cv 的手法，評估每個模型在不同 lambda 下 
# 的 cvm(mean cross-validated error)
cv.lasso = cv.glmnet(x = as.matrix(chem[, -13]), 
                     y = chem[, 13], 
                     alpha = 1,  # lasso
                     family = "binomial")
```
```{R}
# 評估每個模型的 cvm(mean cross-validated error)後
# 取最小 cvm 模型所對應的 lambda
best.lambda_lasso = cv.lasso$lambda.min

# 觀察哪些變數被挑選出來，其係數不為 0的那些
select.ind = which(coef(cv.lasso, s = "lambda.min") != 0)
select.ind = select.ind[-1]-1 # remove `Intercept` and 平移剩下的ind
select.ind # 第幾個變數是重要的 (不看 `Intercept`)
select.varialbes = colnames(chem)[select.ind]
select.varialbes
lasso.lm <- glm(level ~ ., family = 'binomial',data = chem_test[, c(select.varialbes, "level")])
lasso.test <- predict(lasso.lm,chem_test)
cross_validation(lasso.test,ytest)

# 經由 cv 的手法，評估每個模型在不同 lambda 下 
# 的 cvm(mean cross-validated error)
cv.ridge = cv.glmnet(x = as.matrix(chem[, -13]), 
                     y = chem[, 13], 
                     alpha = 0,  # lasso
                     family = "binomial")

# 評估每個模型的 cvm(mean cross-validated error)後
# 取最小 cvm 模型所對應的 lambda
best.lambda = cv.ridge$lambda.min
plot(lasso, xvar='lambda', main="Ridge")
abline(v=log(best.lambda), col="blue", lty=5.5 )
# 觀察哪些變數被挑選出來，其係數不為 0的那些
select.ind = which(coef(cv.lasso, s = "lambda.min") != 0)
select.ind = select.ind[-1]-1 # remove `Intercept` and 平移剩下的ind
select.ind # 第幾個變數是重要的 (不看 `Intercept`)
select.varialbes = colnames(chem)[select.ind]
select.varialbes
ridge.lm <- glm(level ~ ., family = 'binomial',data = chem_train[, c(select.varialbes, "level")])
ridge.test <- predict(ridge.lm,chem_test)
cross_validation(ridge.test,chem_test_y)
```
```{r}
chem <- analyze_data %>% select(,c(polyphenol:ECG,level))
chem$level <- factor(chem$level) %>% as.numeric()
chem$level <- ifelse(chem$level>1,1,0)

chem[,1:12] <- log(chem[,1:12])
chem[,6] <- ifelse(is.infinite(chem[,6]),-6,chem[,6])
test_idx <- sample(1:138,size = 30)
train_idx <- not(1:138 %in% test_idx)
chem_test <- chem[test_idx,]
chem_train <- chem[train_idx,]
chem_test_y <- chem_test$level
```

```{r}
# 1.建立空的線性迴歸(只有截距項)
null <- glm(level~1 ,data=chem_train,family=binomial())
full <- glm(level~. ,data=chem_train,family=binomial())

# 2.使用step()，一個一個把變數丟進去
forward.lm = step(null, 
                  # 從空模型開始，一個一個丟變數，
                  # 最大不會超過完整的線性迴歸
                  # (一定要加上界 upper=full，不可以不加) 
                  scope=list(lower=null, upper=full), 
                  direction="forward")
backward.lm = step(full, 
                  # 這裡可以加下界(lower=null)，也可以不加
                  scope = list(upper=full), 
                  direction="backward")  

summary(forward.lm)

summary(backward.lm)

y_pred_forward <- predict(forward.lm,chem_test)
cross_validation(y_pred_forward,chem_test_y)
y_pred_backward <- predict(backward.lm,chem_test)
cross_validation(y_pred_backward,chem_test_y)
```
```{R}
# lasso & ridge for chem ----
ridge = glmnet(x = as.matrix(chem[, -13]), 
               y = chem[, 13], 
               alpha = 0,
               family = "binomial")

lasso = glmnet(x = as.matrix(chem[, -13]), 
               y = chem[, 13], 
               alpha = 1,
               family = "binomial")

par(mfcol = c(1, 2)) # cool!!
plot(lasso, xvar='lambda', main="Lasso")
plot(ridge, xvar='lambda', main="Ridge")

# 經由 cv 的手法，評估每個模型在不同 lambda 下 
# 的 cvm(mean cross-validated error)
cv.lasso = cv.glmnet(x = as.matrix(chem[, -13]), 
                     y = chem[, 13], 
                     alpha = 1,  # lasso
                     family = "binomial")

# 評估每個模型的 cvm(mean cross-validated error)後
# 取最小 cvm 模型所對應的 lambda
best.lambda_lasso = cv.lasso$lambda.min


plot(lasso, xvar='lambda', main="Lasso")
abline(v=log(best.lambda_lasso), col="blue", lty=5.5 )
# 觀察哪些變數被挑選出來，其係數不為 0的那些
coef(cv.lasso, s = "lambda.min")
select.ind = which(coef(cv.lasso, s = "lambda.min") != 0)
select.ind = select.ind[-1]-1 # remove `Intercept` and 平移剩下的ind
select.ind # 第幾個變數是重要的 (不看 `Intercept`)
select.varialbes = colnames(chem)[select.ind]
select.varialbes
lasso.lm <- glm(level ~ ., family = 'binomial',data = chem_train[, c(select.varialbes, "level")])
print(lasso.lm)
summary(lasso.lm)
lasso.test <- predict(lasso.lm,chem_test)
cross_validation(lasso.test,chem_test_y)
```
```{R}
# 經由 cv 的手法，評估每個模型在不同 lambda 下 
# 的 cvm(mean cross-validated error)
cv.ridge = cv.glmnet(x = as.matrix(chem[, -13]), 
                     y = chem[, 13], 
                     alpha = 0,  # lasso
                     family = "binomial")

# 評估每個模型的 cvm(mean cross-validated error)後
# 取最小 cvm 模型所對應的 lambda
best.lambda = cv.ridge$lambda.min

plot(lasso, xvar='lambda', main="Ridge")
abline(v=log(best.lambda), col="blue", lty=5.5 )
# 觀察哪些變數被挑選出來，其係數不為 0的那些
coef(cv.lasso, s = "lambda.min")
select.ind = which(coef(cv.lasso, s = "lambda.min") != 0)
select.ind = select.ind[-1]-1 # remove `Intercept` and 平移剩下的ind
select.ind # 第幾個變數是重要的 (不看 `Intercept`)
select.varialbes = colnames(chem)[select.ind]
select.varialbes
ridge.lm <- glm(level ~ ., family = 'binomial',data = chem_train[, c(select.varialbes, "level")])
print(ridge.lm)
summary(ridge.lm)
ridge.test <- predict(ridge.lm,chem_test)
cross_validation(ridge.test,chem_test_y)
```
```{r,include = FALSE}
scatter_hist_plot <- function(dat) {
  n = length(colnames(dat))
  for (i in 1:n) 
    {
     for(j in 1:n)
      {
        if(i==j)
        {
          test <- ggplot(data=dat,aes(get(colnames(dat[i]))))+
            geom_histogram(bins = 30,fill = 'darkgreen')+
            labs(x=paste(i,colnames(dat[i]),y=NULL))
        }
        else
        {
          test <- ggplot(data=dat,aes(get(colnames(dat[i])),get(colnames(dat[j]))),colour='green')+
            geom_point()+
            labs(x=paste(i,colnames(dat[i])),y=paste(j,colnames(dat[j])))
        }
        print(test,vp=viewport(width=1/n, 
                               height=1/n,
                               x=((i-1)%%n)/n+1/(2*n),
                               y=((j-1)%%n)/n+1/(2*n)
                               )
              )
      }
    }
}


```


```{r}
test_idx <- sample(1:138,size = 30)
train_idx <- not(1:138 %in% test_idx)
weather_test <- weather[test_idx,]
weather_train <- weather[train_idx,]
weather_test_y <- weather_test$caffeine  
```

```{r}
# 1.建立空的線性迴歸(只有截距項)
null <- lm(caffeine  ~1 ,data=weather_train)
full <- lm(caffeine  ~. ,data=weather_train)

# 2.使用step()，一個一個把變數丟進去
forward.lm = step(null, 
                  # 從空模型開始，一個一個丟變數，
                  # 最大不會超過完整的線性迴歸
                  # (一定要加上界 upper=full，不可以不加) 
                  scope=list(lower=null, upper=full), 
                  direction="forward")
backward.lm = step(full, 
                  # 這裡可以加下界(lower=null)，也可以不加
                  scope = list(upper=full), 
                  direction="backward")  

summary(forward.lm)
summary(backward.lm)

inter <- lm(level  ~. +caffeine*Gallic_Acid*GCG,data=chem_train)
inter.b.lm = step(inter, 
                  # 從空模型開始，一個一個丟變數，
                  # 最大不會超過完整的線性迴歸
                  # (一定要加上界 upper=full，不可以不加) 
                  scope=list(lower=null, upper=inter), 
                  direction="backward")
summary(inter.b.lm)
y_pred_forward <- predict(forward.lm,weather_test)
accuracy(y_pred_forward,weather_test_y)
y_pred_backward <- predict(backward.lm,weather_test)
accuracy(y_pred_backward,weather_test_y)

```
5/13 report
```{r}
```

